/// Simplified Cap'n Proto implementation for development
///
/// This is a placeholder that allows the code to compile without the actual capnp tool
/// In production, this will be replaced with code generated by the Cap'n Proto compiler

// Note: This module provides a development fallback when capnp tool is not available

/// ExtractRequest structure
#[derive(Debug, Clone)]
pub struct ExtractRequest {
    pub request_id: u64,
    pub project_path: String,
    pub language: String,
    pub config: String,
    pub timeout_ms: u32,
    pub version: String,
}

/// ExtractResponse structure
#[derive(Debug, Clone)]
pub struct ExtractResponse {
    pub request_id: u64,
    pub success: bool,
    pub ir: Vec<u8>,
    pub metadata: String,
    pub processing_time_ms: u32,
}

/// ErrorResponse structure
#[derive(Debug, Clone)]
pub struct ErrorResponse {
    pub request_id: u64,
    pub error_code: u32,
    pub error_message: String,
    pub error_details: String,
}

/// Heartbeat structure
#[derive(Debug, Clone)]
pub struct Heartbeat {
    pub timestamp: u64,
    pub extractor_name: String,
    pub status: String,
}

/// Message union for request/response pattern
#[derive(Debug, Clone)]
pub enum ExtractorMessage {
    Request(ExtractRequest),
    Response(ExtractResponse),
    Error(ErrorResponse),
    Heartbeat(Heartbeat),
}

impl ExtractorMessage {
    /// Create a request message
    pub fn new_request(
        request_id: u64,
        project_path: String,
        language: String,
        config: String,
        timeout_ms: u32,
        version: String,
    ) -> Self {
        ExtractorMessage::Request(ExtractRequest {
            request_id,
            project_path,
            language,
            config,
            timeout_ms,
            version,
        })
    }

    /// Create a response message
    pub fn new_response(
        request_id: u64,
        success: bool,
        ir: Vec<u8>,
        metadata: String,
        processing_time_ms: u32,
    ) -> Self {
        ExtractorMessage::Response(ExtractResponse {
            request_id,
            success,
            ir,
            metadata,
            processing_time_ms,
        })
    }

    /// Create an error message
    pub fn new_error(
        request_id: u64,
        error_code: u32,
        error_message: String,
        error_details: String,
    ) -> Self {
        ExtractorMessage::Error(ErrorResponse {
            request_id,
            error_code,
            error_message,
            error_details,
        })
    }

    /// Create a heartbeat message
    pub fn new_heartbeat(timestamp: u64, extractor_name: String, status: String) -> Self {
        ExtractorMessage::Heartbeat(Heartbeat {
            timestamp,
            extractor_name,
            status,
        })
    }
}
